Fix name clash for syntax nodes named syntax
When trying to use https://github.com/mitchellh/tree-sitter-proto, I got this
error:

```
class SyntaxNode extends SyntaxNode {
                         ^

ReferenceError: Cannot access 'SyntaxNode' before initialization
```

This commit simply prepends a _ to the internal SyntaxNode name.